#!/bin/sh

set -euo pipefail

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  # Extract request ID by scraping response headers received above
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Generate the response by any suitable means
  RESPONSE="{\"StatusCode\": 200, \"body\": { \"SOME_ENV_VAR\": \"$SOME_ENV_VAR\", \"SOME_SECRET_ENV_VAR\": \"$SOME_SECRET_ENV_VAR\", \"event\": \"$EVENT_DATA\"} }"

  # Send the response
  curl "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done

