AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-custom-runtime

  Sample SAM Template for sam-app-custom-runtime

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  CustomRuntimeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CustomRuntime:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: ./
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CustomRuntimeApi:
    Description: API Gateway endpoint URL for Prod stage for Custom Runtime function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/custom_runtime/"
  CustomRuntimeFunction:
    Description: Custom Runtime Lambda Function ARN
    Value: !GetAtt CustomRuntimeFunction.Arn
  CustomRuntimeFunctionIamRole:
    Description: Implicit IAM Role created for Custom Runtime function
    Value: !GetAtt CustomRuntimeFunctionRole.Arn
